### ISSUE TITLE
Return pprint insteand of io.write?

### ISSUE THREAD

**Issue by Ismoh** [jagt/pprint.lua#6]
Is it possible to return the pretty printed string instead of writing it to io?

I could use the pretty print string to be returned and stored.

**Comment by jagt** [comment]
There's `pprint.pformat` to do just that.

Cheers!

**Comment by Ismoh** [comment]
pprint.format returns {}.
Is there an example to use?

**Comment by Ismoh** [comment]
Ah! The problem is just me, beeing stupid!
Thanks for the reply!
Have a nice one!
